function  selectedCountryInputs (value){

              if(value==="Algeria") return "Algeria"
              if(value==="Algeria") return "Algérie"
              if(value==="Angola") return "Angola"
              if(value==="Angola") return "L'Angola"
              if(value==="Benin") return "Benin"
              if(value==="Benin") return "Bénin"
              if(value==="Botswana") return "Botswana"
              if(value==="Botswana") return "Botswana"
              if(value==="Burkina_Faso") return "Burkina Faso"
              if(value==="Burkina_Faso") return "Burkina Faso"
              if(value==="Burundi") return "Burundi"
              if(value==="Burundi") return 'Burundi'
              if(value==="Cameroon") return "Cameroon"
              if(value==="Cameroon") return "Cameroun"
              if(value==="Cabo_Verde") return "Cabo Verde"
              if(value==="Cabo_Verde") return "Cabo Verde"
              if(value==="Central_Africa_Republic") return "Central Africa Republic"
              if(value==="Central_Africa_Republic") return "République Centrafricaine"
              if(value==="Chad") return  "Chad"
              if(value==="Chad") return "Tchad"
              if(value==="Comoros") return  "Comoros"
              if(value==="Comoros") return "Comores"
              if(value==="Congo") return  "Congo"
              if(value==="Congo") return "Congo"
              if(value==="Democratic_Republic_Of_The_Congo") return  "Democratic Republic Of The Congo"
              if(value==="Democratic_Republic_Of_The_Congo") return "République Démocratique du Congo"
              if(value==="Djibouti") return  "Djibouti"
              if(value==="Djibouti") return "Djibouti"
              if(value==="Egypt") return  "Egypt"
              if(value==="Egypt") return "Egypte"
              if(value==="Equatorial_Guinea") return  "Equatorial Guinea"
              if(value==="Equatorial_Guinea") return "Guinée Équatoriale"
              if(value==="Eritrea") return  "Eritrea"
              if(value==="Eritrea") return "Érythrée"
              if(value==="Ethiopia") return  "Ethiopia"
              if(value==="Ethiopia") return "Ethiopie"
              if(value==="French_Southern_territory") return "French Southern territory"
              if(value==="French_Southern_territory") return "Territoires du Sud français"
              if(value==="Gabon") return "Gabon"
              if(value==="Gabon") return "Gabon"
              if(value==="Gambia") return "Gambia"
              if(value==="Gambia") return "Gambie"
              if(value==="Ghana") return "Ghana"
              if(value==="Ghana") return "Ghana"
              if(value==="Guinea") return "Guinea"
              if(value==="Guinea") return "Guinée"
              if(value==="Guinea_Bissau") return "Guinea Bissau"
              if(value==="Guinea_Bissau") return "Guinée Bissau"
              if(value==="Cote_DIvoire") return "Cote d'Ivoire"
              if(value==="Cote_DIvoire") return "Côte d'Ivoire"
              if(value==="Kenya") return "Kenya"
              if(value==="Kenya") return "Kenya"
              if(value==="Lesotho") return "Lesotho"
              if(value==="Lesotho") return "Lesotho"
              if(value==="Liberia") return "Liberia"
              if(value==="Liberia") return "Liberia"
              if(value==="Libya") return "Libya"
              if(value==="Libya") return "Libye"
              if(value==="Madagascar") return "Madagascar"
              if(value==="Madagascar") return "Madagascar"
              if(value==="Malawi") return "Malawi"
              if(value==="Malawi") return "Malawi"
              if(value==="Mali") return "Mali"
              if(value==="Mali") return "Mali"
              if(value==="Mauritania") return "Mauritania"
              if(value==="Mauritania") return "Mauritanie"
              if(value==="Mauritius") return "Mauritius"
              if(value==="Mauritius") return "Maurice"
              if(value==="Mayotte") return "Mayotte"
              if(value==="Mayotte") return "Mayotte"
              if(value==="Morocco") return "Morocco"
              if(value==="Morocco") return "Maroc"
              if(value==="Mozambique") return "Mozambique"
              if(value==="Mozambique") return "Mozambique"
              if(value==="Namibia") return "Namibia"
              if(value==="Namibia") return "Namibie"
              if(value==="Niger") return "Niger"
              if(value==="Niger") return "Niger"
              if(value==="Nigeria") return "Nigeria"
              if(value==="Nigeria") return "Nigeria"
              if(value==="Reunion") return "Reunion"
              if(value==="Reunion") return "Réunion"
              if(value==="Rwanda") return "Rwanda"
              if(value==="Rwanda") return "Rwanda"
              if(value==="Saint_Helana") return "Saint Helana"
              if(value==="Saint_Helana") return "Sainte-Hélène"
              if(value==="Sao_Tome_And_Principe") return  "Sao Tome And Principe"
              if(value==="Sao_Tome_And_Principe") return "Sao Tomé et Principe"
              if(value==="Senegal") return  "Senegal"
              if(value==="Senegal") return "Sénégal"
              if(value==="SeyChelles") return  "SeyChelles"
              if(value==="SeyChelles") return "Les Seychelles"
              if(value==="Sierra_leon") return  "Sierra leon"
              if(value==="Sierra_leon") return "Sierra Leone"
              if(value==="Somalia") return  "Somalia"
              if(value==="Somalia") return "Somalie"
              if(value==="South_Africa") return  "South Africa"
              if(value==="South_Africa") return "Afrique du Sud"
              if(value==="South_Sudan") return  "South Sudan"
              if(value==="South_Sudan") return "Soudan du sud"
              if(value==="Sudan") return  "Sudan"
              if(value==="Sudan") return "Soudan"
              if(value==="Swaziland") return  "Swaziland"
              if(value==="Swaziland") return "Swaziland"
              if(value==="Tanzania") return  "Tanzania"
              if(value==="Tanzania") return "Tanzanie"
              if(value==="Togo") return  "Togo"
              if(value==="Togo") return "Togo"
              if(value==="Tunisia") return  "Tunisia"
              if(value==="Tunisia") return "Tunisie"
              if(value==="Uganda") return  "Uganda"
              if(value==="Uganda") return "Ouganda"
              if(value==="Western_Sahara") return  "Western Sahara"
              if(value==="Western_Sahara") return "Sahara occidental"
              if(value==="Zambia") return  "Zambia"
              if(value==="Zambia") return "Zambie"
              if(value==="Zimbabwe") return "Zimbabwe"
              if(value==="Zimbabwe") return "Zimbabwe"
            
              if(value==="Apartment") return "Apartment"
              if(value==="Apartment") return "Apartement"
              if(value==="Single Room") return "Single Room"
              if(value==="Single Room") return "Chambre simple"
              if(value==="Office") return "Office"
              if(value==="Office") return "Bureau"
              if(value==="Store/Shop") return "Store/Shop"
              if(value==="Store/Shop") return "Boutique"
              if(value==="Land") return "Land"
              if(value==="Land") return "Terre"
              if(value==="Condos") return "Condos"
              if(value==="Condos") return "Condos"

              if(value==="Buéa") return "Buea"
              if(value==="Yaoundé") return "Yaounde"
              if(value==="Limbé") return "Limbe"
              if(value==="Sétif") return "Setif"
              if(value==="Aïn Témouchent") return "Aïn Temouchent"
              if(value==="Sédrata") return "Sedrata"
              if(value==="Athiémè") return "Athieme"
              if(value==="Bembèrèkè") return "Bembereke"
              if(value==="Bétérou") return "Beterou"
              if(value==="Boukoumbé") return "Boukoumbe"
              if(value==="Comè") return "Come"
              if(value==="Cové") return "Cove"
              if(value==="Dassa-Zoume") return "Dassa-Zoume"
              if(value==="Kérou") return "Kerou"
              if(value==="Kétou") return "Ketou"
              if(value==="Kouandé") return "Kouande"
              if(value==="Péhonko") return "Pehonko"
              if(value==="Pobè") return "Pobe"
              if(value==="Sakété") return "Sakete"
              if(value==="Savé") return "Save"
              if(value==="Ségbana") return "Segbana"
              if(value==="Tanguiéta") return "Tanguieta"
              if(value==="Bagré") return "Bagre"
              if(value==="Batié") return "Batie"
              if(value==="Bogandé") return "Bogande"
              if(value==="Boussé") return "Bousse"
              if(value==="Diébougou") return "Diebougou"
              if(value==="Gayéri") return "Gayeri"
              if(value==="Houndé") return "Hounde"
              if(value==="Koupéla") return "Koupela"
              if(value==="Léo") return "Leo"
              if(value==="Méguet") return "Meguet"
              if(value==="Réo") return "Reo"
              if(value==="Saponé") return "Sapone"
              if(value==="Séguénéga") return "Seguenega"
              if(value==="Tikaré") return "Tikare"
              if(value==="Ziniaré") return "Ziniare"
              if(value==="Bangangté") return "Bangangte"
              if(value==="Bélabo") return "Belabo"
              if(value==="Édéa") return "Edea"
              if(value==="Eséka") return "Eseka"
              if(value==="Kaélé") return "Kaele"
              if(value==="Kékem") return "Kekem"
              if(value==="Kousséri") return "Kousseri"
              if(value==="Mamfe") return "Mamfe"
              if(value==="Ngaoundéré") return "Ngaoundere"
              if(value==="Njombé") return "Njombe"
              if(value==="Nkambé") return "Nkambe"
              if(value==="Sangmelima") return "Sangmelima"
              if(value==="Bossembélé") return "Bossembele"
              if(value==="Kembé") return "Kembe"
              if(value==="Adda-Douéni") return "Adda-Doueni"
              if(value==="Antsahé") return "Antsahe"
              if(value==="Chamlé") return "Chamle"
              if(value==="Dembéni") return "Dembeni"
              if(value==="Dimadjou-Mdé") return "Dimadjou-Mde"
              if(value==="Dzahadjou Lamzandé") return "Dzahadjou Lamzande"
              if(value==="Hahaya-Aéroport") return "Hahaya-Aeroport"
              if(value==="Héléindjé-Salimani-Zounda") return "Heleindje-Salimani-Zounda"
              if(value==="Hirohé") return "Hirohe"
              if(value==="Djoièzi") return "Djoiezi"
              if(value==="Loutété") return "Loutete"
              if(value==="San Antonio de Palé") return "San Antonio de Pale"
              if(value==="Booué") return "Booue"
              if(value==="Étéké") return "Eteke"
              if(value==="Médouneu") return "Medouneu"
              if(value==="Mékambo") return "Mekambo"
              if(value==="Lambaréné") return "Lambarene"
              if(value==="Mékambo") return "Mekambo"
              if(value==="Ndendé") return "Ndende"
              if(value==="Ndjolé") return "Ndjole"
              if(value==="Omboué") return "Omboue"
              if(value==="Setté Cama") return "Sette Cama"
              if(value==="Boké") return "Boke"
              if(value==="Dubréka") return "Dubreka"
              if(value==="Forécariah") return "Forecariah"
              if(value==="Guéckédou") return "Gueckedou"
              if(value==='Kérouané') return 'Kerouane'
              if(value==="Labé") return 'Labe'
              if(value==="Lélouma") return "Lelouma"
              if(value==="Nzérékoré") return "Nzerekore"
              if(value==="Télimélé") return "Telimele"
              if(value==="Tougué") return "Tougue"
              if(value==="Bouaké") return "Bouake"
              if(value==="San-Pédro") return "San-Pedro"
              if(value==="Soubré") return "Soubre"
              if(value==="Bouaflé") return "Bouafle"
              if(value==="Adzopé") return "Adzope"
              if(value==="Séguéla") return "Seguela"
              if(value==="Oumé") return "Oume"
              if(value==="Odienne") return "Odienne"
              if(value==="Duékoué") return "Duekoue"
              if(value==="Danané") return "Danane"
              if(value==="Tingréla") return "Tingrela"
              if(value==="Agnibilékrou") return "Agnibilekrou"
              if(value==="Zuénoula") return "Zuenoula"
              if(value==="Tiassale") return "Tiassale"
              if(value==="Akoupe") return "Akoupe"
              if(value==="Ségou") return "Segou"
              if(value==="Mandé") return "Mande"
              if(value==="Kolondiéba") return "Kolondieba"
              if(value==="Troungoumbé") return "Troungoumbe"
              if(value==="Ténenkou") return "Tenenkou"
              if(value==="Fégui") return "Fegui"
              if(value==="Kaédi") return "Kaedi"
              if(value==="Zouérat") return "Zouerat"
              if(value==="Sélibabi") return "Selibabi"
              if(value==="Sélibaby") return "Selibaby"
              if(value==="Néma") return "Nema"
              if(value==="Bababé") return "Bababe"
              if(value==="Bouéni") return "Boueni"
              if(value==="Dembéni") return "Dembeni"
              if(value==="Kani-Kéli") return "Kani-Keli"
              if(value==="Salé") return "Sale"
              if(value==="Aguié") return "Aguie"
              if(value==="Balléyara") return "Balleyara"
              if(value==="Birni Ngaouré") return "Birni Ngaoure"
              if(value==="Filingué") return "Filingue"
              if(value==="Gouré") return "Goure"
              if(value==="Illéla") return "Illela"
              if(value==="Maïné-Soroa") return "Maïne-Soroa"
              if(value==="Téra") return "Tera"
              if(value==="Tillabéri") return "Tillaberi"
              if(value==="L'Étang-Salé") return "L'Étang-Sale"
              if(value==="Saint-André") return "Saint-Andre"
              if(value==="São Tomé") return "São Tome"
              if(value==="Thiès") return "Thies"
              if(value==="Mbacké") return "Mbacke"
              if(value==="Vélingara") return "Velingara"
              if(value==="Sédhiou") return "Sedhiou"
              if(value==="Sébikhotane") return "Sebikhotane"
              if(value==="Kédougou") return "Kedougou"
              if(value==="Nguékhokh") return "Nguekhokh"
              if(value==="Mékhé") return "Mekhe"
              if(value==="Kébémer") return "Kebemer"
              if(value==="Guinguinéo") return "Guinguineo"
              if(value==="Lomé") return "Lome"
              if(value==="Sokodé") return "Sokode"
              if(value==="Kpalimé") return "Kpalime"
              if(value==="Atakpamé") return "Atakpame"
              if(value==="Tsévié") return "Tsevie"
              if(value==="Aného") return "Aneho"
              if(value==="Notsé") return "Notse"
              if(value==="Amlamé") return "Amlame"

            
              if(value==="None") return "None"
              if(value==="None") return "Rien"
              if(value==="Garage-Pool-Flowers-Garden-Playground") return "Garage-Pool-Flowers-Garden-Playground"
              if(value==="Garage-Pool-Flowers-Garden-Playground") return "Garage-Piscine-Fleurs-Jardin-Aire de Jeux"
              if(value==="Garage-Pool-Flowers-Garden") return "Garage-Pool-Flowers-Garden"
              if(value==="Garage-Pool-Flowers-Garden") return "Garage-Piscine-Fleurs-Jardin"
              if(value==="Pool-Flowers-Garden-Playground") return "Pool-Flowers-Garden-Playground"
              if(value==="Pool-Flowers-Garden-Playground") return "Piscine-Fleurs-Jardin-Aire de Jeux"
              if(value==="Flowers-Garden-Playground") return "Flowers-Garden-Playground"
              if(value==="Flowers-Garden-Playground") return "Fleurs-Jardin-Aire de Jeux"
              if(value==="Garage-Pool-Flowers") return "Garage-Pool-Flowers"
              if(value==="Garage-Pool-Flowers") return "Garage-Piscine-Fleurs"
              if(value==="Garden-Playground") return "Garden-Playground"
              if(value==="Garden-Playground") return "Jardin-Aire de jeux"
              if(value==="Pool-Flowers") return "Pool-Flowers"
              if(value==="Pool-Flowers") return "Piscine-Fleurs"
              if(value==="Garage-Playground") return "Garage-Playground"
              if(value==="Garage-Playground") return "Garage-Cour de récréation"
              if(value==="Garage-Pool") return "Garage-Pool"
              if(value==="Garage-Pool") return "Garage-Piscine"
              if(value==="Garage-Garden") return "Garage-Garden"
              if(value==="Garage-Garden") return "Garage-Jardin"
              if(value==="Garage-Flowers") return "Garage-Flowers"
              if(value==="Garage-Flowers") return "Garage-Fleurs"
              if(value==="Pool-Garden") return "Pool-Garden"
              if(value==="Pool-Garden") return "Piscine-Jardin"
              if(value==="Pool-Playground") return "Pool-Playground"
              if(value==="Pool-Playground") return "Piscine-Aire de jeux"
              if(value==="Flowers-Garden") return "Flowers-Garden"
              if(value==="Flowers-Garden") return "Fleurs-Jardin"
              if(value==="Flower-Playground") return "Flower-Playground"
              if(value==="Flower-Playground") return "Fleur-Aire de jeux"
              if(value==="Garage") return "Garage"
              if(value==="Garage") return "Garage"
              if(value==="Pool") return "Pool"
              if(value==="Pool") return "Piscine"
              if(value==="Flowers") return "Flowers"
              if(value==="Flowers") return "Fleur"
              if(value==="Garden") return "Garden"
              if(value==="Garden") return "Jardin"
              if(value==="Playground") return "Playground"
              if(value==="Playground") return "Aire de jeux"
            
              if(value==="Rental") return "Rental"
              if(value==="Rental") return "De Location"
              if(value==="Sale") return "Sale"
              if(value==="Sale") return "Vente"
            
            
              if(value==="I am the Owner") return "I am the Owner"
              if(value==="I am the Owner") return "Je suis le propriétaire"
              if(value==="I am an Agent / Broker") return "I am an Agent / Broker"
              if(value==="I am an Agent / Broker") return "Je suis un agent / courtier"
              if(value==="I am a Property Manager") return "I am a Property Manager"
              if(value==="I am a Property Manager") return "Je suis un Property Manager"
            
            
              return value
            }
            
            
            
export default selectedCountryInputs  